POST http://localhost:8080/brews
Content-Type: application/json

{
    "coffeeName": "playa",
    "coffeeGrams": 18,
    "grindSize": 4,
    "waterGrams": 200,
    "brewingMethod": "kalita",
    "brewTime": 90
}

